#!/bin/bash

set -o nounset

restore_volume(){
    local path_file="$1"
    local name_volume="$2"
    local name_backup_archive=$(basename "$path_file")

    if [ -z "$name_volume" ] || [ -z "$path_file" ]; then
        printf "Error: Not enough arguments\n"
        exit 1
    fi

    if [ ! -f "$path_file" ]; then
        printf "File ${path_file} parsing error\n"
    fi

    if ! docker volume inspect --format '{{.Name}}' "$name_volume" > /dev/null;
    then
        printf "Error: Volume $name_volume does not exist\nVolume initialization\n"
        docker volume create "$name_volume" > /dev/null
    fi

    docker run --rm -v "$name_volume":/volume -v "$path_file":/"${name_backup_archive}" ubuntu tar --totals -xvzf "$name_backup_archive" -C /volume

    printf "\nRecovery of the ${name_volume} volume is complete\n"
}

restore_volume "$@"